# .pipe.yml - Project's pipeline

name: vite-plugin-librejs
image: docker.io/denoland/deno:debian-2.7.12

env:
    PATH: /usr/bin/deno:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin/:/sbin/:bin

steps:
    - name: Lint
      parallel: true
      run: |
          /usr/bin/deno lint

    - name: Check
      parallel: true
      run: |
          /usr/bin/deno check
